name: powergenome
channels:
  - conda-forge
  # - defaults
dependencies:
  - python=3.10 # Remove for tox.ini & setup.py
  - pip
  - jupyterlab
  - black
  - pytest
  - beautifulsoup4
  - pyyaml
  - isort
  - pre-commit
  - conda-forge::nb_conda_kernels
  - statsmodels>=0.13
  - conda-forge::python-dotenv
  - conda-forge::flatten-dict
  - conda-forge::ruamel.yaml
  - conda-forge::frozendict
  - conda-forge::hypothesis[pandas]
  - numpy
  - openpyxl>=3.0
  - duckdb

  # GIS dependencies from conda-forge (except geopandas - handled by pip)
  - conda-forge::fiona
  - conda-forge::pyogrio
  - conda-forge::shapely

  # Install via pip for better dependency resolution
  - pip:
    - geopandas>=0.12
