BarConvTol: 1.0e-08
CES: 3
CES_Adjustment: 0
CO2Cap: 2
CapacityReserveMargin: 0
Crossover: -1
Distr_Loss_Segments: 0
Distr_Margin_LV_Segments: 0
Dual_MIP: 0
Externalities: 0
Feasib_Tol: 1.0e-06
GenXScalingFactor: 1000
HeatMarket: 0
LDS: 0
MacOrWindows: Mac
Method: 4
NetworkExpansion: 1
NumericFocus: 1
OperationWrapping: 2
Optimal_Tol: 1.0e-06
PrintModel: 0
RPS: 3
RPS_Adjustment: 0
Reserves: 0
RoundingDigits: 3
Solver: CLP
Specific_Share: 0
StorageLosses: 0
Trading: 0
Trans_Loss_Segments: 1
UCommit: 2
case_id: p1
case_name: Tech_CES_with_RPS
pTolerance: 0.05
year: '2045'
